name: blckur
version: 1.0.0
dependencies:
  angular:
    git: https://github.com/zachhuff386/angular.dart.git
  web_components: ">=0.10.5"
  browser: ">=0.10.0+2"
  barback: ">=0.14.1"
  logging: ">=0.9.3"
  polymer: ">=0.15.5"
  core_elements: ">=0.6.0"
  paper_elements: ">=0.6.1"
  initialize: "0.5.1+3"
transformers:
- blckur
- angular
- polymer:
    entry_points: web/index.html
